### PR TITLE
Adjust phrasing in sensors-and-actuator docs

### PR DESCRIPTION
**Pull request by Dobiasd**

### CODE REVIEW

**Comment by Dobiasd** [comment]
`1 of 1 commits are not conventional commit compliant`

Oops. :grimacing:

**Comment by dennisschroeder** [comment]
Thx for the pull request @Dobiasd! I should have mentioned somewhere that I am using conventional commits. Check this page for details: https://www.conventionalcommits.org/en/v1.0.0/. So your commit message had to be prefixed with"docs:".

**Comment by Dobiasd** [comment]
Ok, thx. I've squashed the three commits (mine, your's, and the merge commit) into one with a confirming commit message, and force-pushed to the branch.

**Comment by Dobiasd** [comment]
Ok, now we have new conflicts. Too much git chaos for me. I'll create a new branch and PR. :wink:

**Pull request closed without merging**
